# Generated by Django 3.1.2 on 2020-10-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='id',
        ),
        migrations.AlterField(
            model_name='community',
            name='acronym',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
