# Generated by Django 3.1.2 on 2020-11-08 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20201020_1335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('int_domain', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('gitlab', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('osm_id', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.community')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
